global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK'
  telegram_api_url: 'https://api.telegram.org'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@yourdomain.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-specific-password'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 1h
      continue: true
    
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 1m
      repeat_interval: 2h
      continue: true
    
    - match_re:
        service: ^(trading|arbitrage)$
      receiver: 'trading-team'
      group_wait: 30s
      routes:
        - match:
            type: performance
          receiver: 'performance-alerts'
        - match:
            type: security
          receiver: 'security-alerts'
    
    - match_re:
        service: ^(infrastructure|system)$
      receiver: 'devops-team'
      group_wait: 30s

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'instance']

receivers:
  - name: 'default'
    slack_configs:
      - channel: '#monitoring'
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        send_resolved: true
    
  - name: 'critical-alerts'
    slack_configs:
      - channel: '#critical-alerts'
        title: '{{ template "slack.critical.title" . }}'
        text: '{{ template "slack.critical.text" . }}'
        send_resolved: true
    telegram_configs:
      - bot_token: 'YOUR_BOT_TOKEN'
        chat_id: YOUR_CHAT_ID
        parse_mode: 'HTML'
        message: '{{ template "telegram.critical" . }}'
    email_configs:
      - to: 'oncall@yourdomain.com'
        send_resolved: true
    
  - name: 'warning-alerts'
    slack_configs:
      - channel: '#warnings'
        title: '{{ template "slack.warning.title" . }}'
        text: '{{ template "slack.warning.text" . }}'
        send_resolved: true
    
  - name: 'trading-team'
    slack_configs:
      - channel: '#trading-alerts'
        title: '{{ template "slack.trading.title" . }}'
        text: '{{ template "slack.trading.text" . }}'
        send_resolved: true
    telegram_configs:
      - bot_token: 'YOUR_BOT_TOKEN'
        chat_id: YOUR_TRADING_CHAT_ID
        parse_mode: 'HTML'
        message: '{{ template "telegram.trading" . }}'
    
  - name: 'performance-alerts'
    slack_configs:
      - channel: '#performance'
        title: '{{ template "slack.performance.title" . }}'
        text: '{{ template "slack.performance.text" . }}'
        send_resolved: true
    
  - name: 'security-alerts'
    slack_configs:
      - channel: '#security'
        title: '{{ template "slack.security.title" . }}'
        text: '{{ template "slack.security.text" . }}'
        send_resolved: true
    telegram_configs:
      - bot_token: 'YOUR_BOT_TOKEN'
        chat_id: YOUR_SECURITY_CHAT_ID
        parse_mode: 'HTML'
        message: '{{ template "telegram.security" . }}'
    email_configs:
      - to: 'security@yourdomain.com'
        send_resolved: true
    
  - name: 'devops-team'
    slack_configs:
      - channel: '#devops'
        title: '{{ template "slack.devops.title" . }}'
        text: '{{ template "slack.devops.text" . }}'
        send_resolved: true
    telegram_configs:
      - bot_token: 'YOUR_BOT_TOKEN'
        chat_id: YOUR_DEVOPS_CHAT_ID
        parse_mode: 'HTML'
        message: '{{ template "telegram.devops" . }}' 