groups:
  - name: ArbitrageAlerts
    rules:
      - alert: HighGasPrice
        expr: current_gas_price_gwei > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High gas price detected
          description: Gas price has been above 100 Gwei for 5 minutes

      - alert: LowSuccessRate
        expr: (successful_arbitrage_transactions_total / arbitrage_transactions_total * 100) < 80
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: Low transaction success rate
          description: Transaction success rate has fallen below 80% in the last 15 minutes

      - alert: SlowExecutionTime
        expr: rate(transaction_execution_time_seconds_bucket[5m])[0] > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow transaction execution
          description: Transactions are taking longer than 2 seconds to execute

      - alert: NegativeProfitMargin
        expr: sum(rate(current_profit_usd[1h])) < 0
        for: 30m
        labels:
          severity: critical
        annotations:
          summary: Negative profit margin
          description: Overall profit has been negative for the last 30 minutes

      - alert: HighMemoryUsage
        expr: memory_usage_bytes{component="arbitrage_agent"} > 1e9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: Arbitrage agent is using more than 1GB of memory

      - alert: HighCPUUsage
        expr: cpu_usage_percent{component="arbitrage_agent"} > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: Arbitrage agent CPU usage is above 80%

      - alert: DEXLatencySpike
        expr: rate(dex_latency_seconds_bucket[5m])[0] > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: DEX latency spike
          description: DEX interaction latency is above 1 second

      - alert: StrategyUnderperformance
        expr: |
          sum(rate(strategy_profit_usd[1h])) by (strategy_name) < 
          avg(rate(strategy_profit_usd[24h])) by (strategy_name) * 0.5
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: Strategy underperformance
          description: Strategy profit is less than 50% of 24h average

      - alert: GasEstimationError
        expr: abs(gas_estimation_accuracy) > 20
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Gas estimation inaccuracy
          description: Gas estimation error is more than 20% off actual usage

      - alert: FlashLoanFailure
        expr: |
          sum(rate(dex_transactions_total{strategy="flash_loan_arbitrage",status="failure"}[15m])) /
          sum(rate(dex_transactions_total{strategy="flash_loan_arbitrage"}[15m])) > 0.2
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: High flash loan failure rate
          description: Flash loan failure rate is above 20% in the last 15 minutes

      - alert: TokenPairInactivity
        expr: absent(token_pair_volume_total) == 1
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: Token pair inactivity
          description: No trading activity detected for monitored token pairs

      - alert: MultiHopFailure
        expr: |
          sum(rate(dex_transactions_total{strategy="multi_hop_arbitrage",status="failure"}[15m])) /
          sum(rate(dex_transactions_total{strategy="multi_hop_arbitrage"}[15m])) > 0.3
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: High multi-hop failure rate
          description: Multi-hop arbitrage failure rate is above 30% in the last 15 minutes 